Added IsEvenOrOdd method
drtaupier/C-Basic pull request #11
Opened 2020-04-26 19:35 UTC by drtaupier

![image](https://user-images.githubusercontent.com/25469950/80317746-92dc9400-87d3-11ea-99f1-562ce2dc206c.png)

2020-04-26 23:06 UTC, mriverap commented
Please change the screenshot to a sample of the execution.

2020-04-26 23:11 UTC, mriverap requested changes
Link the appropriate Issue to this PR.

2020-04-26 23:11 UTC, mriverap commented on CSharpBasics/BasicProblems.cs
> +            if (num1 % 2 == 0)
Great!

2020-04-27 00:46 UTC, drtaupier commented on CSharpBasics/BasicProblems.cs
> +            if (num1 % 2 == 0)
![image](https://user-images.githubusercontent.com/25469950/80324486-f62feb80-87fe-11ea-8fc6-24652f2a052b.png)

2020-04-27 00:47 UTC, drtaupier commented on CSharpBasics/BasicProblems.cs
> +            if (num1 % 2 == 0)
![image](https://user-images.githubusercontent.com/25469950/80324512-25465d00-87ff-11ea-8fe1-de87543b50ab.png)

2020-04-29 23:16 UTC, mriverap approved these changes

2020-04-29 23:16 UTC, merged