What is your age
drtaupier/C-Basic pull request #16
Opened 2020-04-27 08:06 UTC by drtaupier

![image](https://user-images.githubusercontent.com/25469950/80348834-5ee98900-883c-11ea-8515-e7b62292e092.png)

2020-04-27 16:00 UTC, mriverap requested changes
Please include only changes that belong to this problem.

2020-04-27 16:00 UTC, mriverap commented on CSharpBasics/BasicProblems.cs
> -            Console.WriteLine($"The result is: {result}" );
This belongs to another PR.

2020-04-27 16:00 UTC, mriverap commented on CSharpBasics/BasicProblems.cs
>          public static void MultiplyTwoNumbers()
This belongs to another PR

2020-04-27 16:00 UTC, mriverap commented on CSharpBasics/BasicProblems.cs
> +            if (num1 % 2 == 0)
All this belongs to another PR

2020-04-27 16:00 UTC, mriverap commented on CSharpBasics/BasicProblems.cs
> +            if (monthOfBirth > monthNow)
Very good. You can combine the two "if" statements into one.

2020-04-28 00:13 UTC, drtaupier commented on CSharpBasics/BasicProblems.cs
> +            if (monthOfBirth > monthNow)
Done prima. now its less code 👍

2020-04-29 23:37 UTC, mriverap approved these changes

2020-04-29 23:37 UTC, mriverap commented on CSharpBasics/BasicProblems.cs
> +            Console.WriteLine($"The result is: {sum / times}");
This belongs in a different PR.

2020-04-29 23:37 UTC, mriverap commented on CSharpBasics/BasicProblems.cs
> +            if (monthOfBirth > monthNow || monthOfBirth == monthNow && dayOfBirth > dayNow)
This is the idea, but there is a potential error here. Did you check if it works as expected?

2020-04-29 23:37 UTC, mriverap commented on CSharpBasics/Program.cs
> +                            BasicProblems.average();
This is for a different PR.

2020-04-29 23:37 UTC, merged